### DISCUSSION TITLE
image not opened when press enter on it

### DISCUSSION THREAD

**Discussion by OriLiMu** [sxyazi/yazi#1175] [1. Q&A]
when I move cursor on `jpg` or `png` file and press <kbd>Enter</kbd>. 

The file not opened. The file association is set. 
```fish
> xdg-mime query default image/png                                  ╯
org.kde.gwenview.desktop

> xdg-mime query default image/jpeg                                ─
org.kde.gwenview.desktop
```

`yazi.toml`
```toml
[open]
rules = [

	{ mime = "image/*", use = [ "open", "reveal" ] },

```

**Comment by xfzv** [comment]
Weird, works fine here. What is the content of `open` in `yazi.toml`? Mine:

```toml
[opener]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
```

I'm not using Gwenview but qimgv:

```console
% xdg-mime query default image/png
qimgv.desktop

% xdg-mime query default image/jpeg
qimgv.desktop
```

```console
% yazi --version                                                                                                           
Yazi 0.2.5 (f1cf136 2024-06-23)
```

I guess you can open jpg/png files from Dolphin just fine?
