### DISCUSSION TITLE
how to use nvim to open the current file ?

### DISCUSSION THREAD

**Discussion by OriLiMu** [sxyazi/yazi#1252] [1. Q&A] [answered]
`{ on = [ "e" ],         run = "shell --block --confirm nvim  $0",  desc = "Open the selected files" },`

This command just open nvim but wont edit the current file.

**Comment by AnirudhG07** [comment]
Well there's a default keybinding "Enter" and "o", or you can use "O" to select how to open the file in(including $EDITOR). Why is there a need to complicate this???

And if you really want to use "e" as your keybinding for it, you can add this at the bottom -
```toml
[[manager.prepend_keymap]]
on = ["e"]
run = "open"
desc = "Open the selected file"
```
