### DISCUSSION TITLE
Editing read-only files with root privileges (`sudo`)

### DISCUSSION THREAD

**Discussion by Anakinjh** [sxyazi/yazi#1301] [1. Q&A]
Is there a way to configure yazi to prompt for a password and edit read-only files in the root directory. 

If I were to edit things like an sddm config or any file in /etc/nixos, I need sudo privileges. The only way I've found to move to those files through yazi then edit them is to start yazi with sudo, but unless I copy my config to the system it doesn't use my user's config. 

My other idea was of course to write the files to a temp file in my user's home directory and then sudo mv the file after but that's clunky. 

Is there some secure way to enable this functionality? I don't want to change the sudoers file to no longer require it if I don't need to. Or is this not really an issue most people have?

**Comment by AnirudhG07** [comment]
There is a plugin [sudo.yazi](https://github.com/TD-Sky/sudo.yazi), with which you can perform sudo actions from inside yazi without moving your files here and there. Check it out.

**Reply by xfzv** [reply]
Unless I'm mistaken, this plug-in doesn't seem to allow editing files as root, e.g. `sudoedit $@`

**Comment by sxyazi** [comment]
If you just need to edit files, you can achieve this by customizing the opener:

```toml
# yazi.toml
[opener]
edit = [
  { run = 'nvim "$@"', desc = "nvim", block = true },
  { run = 'sudo nvim "$@"', desc = "sudo nvim", block = true }
]
```

You can also bind it to a shortcut key:

```toml
# keymap.toml
[[manager.prepend_keymap]]
on   = [ "e" ]
run  = '''shell 'sudo nvim "$@"' --block --confirm'''
desc = "Sudo nvim"
```

If you need to copy, move, or rename files with root privileges, check out the [sudo.yazi](https://github.com/TD-Sky/sudo.yazi) plugin like @AnirudhG07 mentioned

---

Docs:

- https://yazi-rs.github.io/docs/configuration/yazi#opener
- https://yazi-rs.github.io/docs/configuration/keymap#manager.shell
