### DISCUSSION TITLE
keymap to start a tmux session

### DISCUSSION THREAD

**Discussion by dhruvindsd-dev** [sxyazi/yazi#1303] [1. Q&A] [answered]
How do I create a keymap to start a tmux session from the dir I'm currently in?

**Comment by AnirudhG07** [comment, marked as answer]
Here you go. Set your own keybinding, I have just given an example
```toml
[[manager.prepend_keymap]]
on  = [ "t", "x" ] 
run  = "shell tmux --block --confirm"
desc  = "Open tmux from current directory"
```
