### DISCUSSION TITLE
Select non-adjacent files (arbitrary selection)

### DISCUSSION THREAD

**Discussion by Bad3r** [sxyazi/yazi#1367] [1. Q&A] [answered]
Hello,
I read the documentation and I can't find an option to select non-adjacent files (arbitrary selection) e.g.

1. file
2. file
3. file
4. file

How can I select the files 1 and 3 without selecting file 2?

**Comment by SolitudeSF** [comment, marked as answer]
you select files with spacebar

**Comment by AnirudhG07** [comment]
There is no default to select alternate files otherwise anyone would want some or the other pattern. Here are few things and solution you might wanna know - 
1) select a file with space bar(as mentioned above)
2) select all files with ctrl A
3) make your own keybinding with you pattern. For example - 
```toml
[[manager.prepend_keymap]]
on  = [ "e", "e" ]
run = ["select --state=none", "arrow 2", "select --state=none"] 
desc  = "Select alternate files"
```
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/9c150d55-27ec-4297-a337-b0fb1b917c7d">
You can set your own keybindings too
