### DISCUSSION TITLE
Enter and l behave differently

### DISCUSSION THREAD

**Discussion by AnirudhG07** [sxyazi/yazi#1398] [1. Q&A]
This issue happens rarely but it happens. When i press enter to a file, it opens a previously opened file in same differently (because i was seeing each file many times). while when i press 'l', it always open the current file. I cannot share any reproducing steps cause it just happens rarely.

Here are my keybindings for each - 
```toml
[[manager.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass --args=smart_enter"
desc = "Recursively enter child directory, skipping children with only a single subdirectory"
```
```toml
[manager]
keymap = [
	{ on = "<Enter>",   run = "open",                        desc = "Open the selected files" }, 
]
```
Any particular reason this maybe happening?
