### DISCUSSION TITLE
compress plugin + clear selected files/folders

### DISCUSSION THREAD

**Discussion by og900aero** [sxyazi/yazi#1447] [1. Q&A]
I use compress.yazi plugin, but I have a problem with that. When compressed files/folders, then not clear selected files/folders. I try add to keybind the escape or unyank command, but the unyank and escape command run before compress (I thinkv because compress plugin request panel for name). The developer of the compress plugin doesn't want to deal with this, and I don't understand the LUA language. How to call a command under init.lua?So how do I call escape or unyank?

**Comment by xfzv** [comment]
This works for me, the items that have just been compressed are no longer selected once the archive has been created:

```toml
[[manager.prepend_keymap]]
on = ["<your_keymap>"]
run = ["plugin compress", "select_all --state=false"]
desc = "Archive selected files"
```
