### DISCUSSION TITLE
Stop yazi from opening extracted directory in GUI file Manager

### DISCUSSION THREAD

**Discussion by higoswami** [sxyazi/yazi#1663] [1. Q&A] [answered]
Hello, I'm using `yazi` on my remote linux machine, which i mostly access using ssh with Zellij
Whenever i try to extract a `.tar.gz` file using `<Enter>` it gets stuck at 99%

![image](https://github.com/user-attachments/assets/1f5eb741-cc3a-41e1-aae2-aab92bd2ae15)

> When i did the same thing using TigerVNC, I realised that yazi actually opens a GUI file explorer after extraction (which is not possible in case of ssh)

This can be confirmed with this msg as well:
![image](https://github.com/user-attachments/assets/9412cab6-a2bf-45ff-be16-858048a56505)

So i decided to add these lines to my `yazi.toml` file:

```toml
[open]
prepend_rules = [
	# Only Decompress and Unarchive. Do not open
	{ mime = "application/{,g}zip", use = [ "extract" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract" ] }
]
```

But somehow `yazi` is still trying to open the extracted files which i do not want. 

Why would i like to open my extracted files in a GUI file-manager when I'm already using `yazi` (a file manager)
