### DISCUSSION TITLE
Update image preview?

### DISCUSSION THREAD

**Discussion by flexbusterman** [sxyazi/yazi#1675] [1. Q&A] [answered]
I have added bindings for rotating images. For example:

[[manager.prepend_keymap]]
on = [ ">" ]
run = 'shell "for file in \"$@\"; do magick \"$file\" -rotate 90 \"${file%}\"; done" --confirm'
desc = "Rotate selected images clockwise"

The image file rotates properly, but the image preview in Yazi remains unchanged and the text "Empty file" appears on top of the preview.
If I select another file and then select the rotated image, the preview is regenerated and shows the rotation as expected.

Is there a way to manually refresh the preview within the keymap script that I could add, or possible other fixes?

New user, really enjoying Yazi! Thanks in advance!

**Comment by AnirudhG07** [comment, marked as answer]
If you want to refresh, you can use "refresh" in run.
```toml
[[manager.prepend_keymap]]
on = [ ">" ]
run = ['shell "for file in "$@"; do magick "$file" -rotate 90 "${file%}"; done" --confirm', "refresh"]
desc = "Rotate selected images clockwise"
```
Check if this works for you or not
