### DISCUSSION TITLE
Shouldn't yazi have default keymaps to reload configs and quit?

### DISCUSSION THREAD

**Discussion by YousufSSyed** [sxyazi/yazi#1755] [1. Q&A]
I did some looking up of both but it seems like there aren't default keymaps, I did find I can make a keymap to quit yazi but it's tedious to do repeatedly when testing configs: https://yazi-rs.github.io/docs/configuration/keymap/#manager.quit.

I made this mapping:
```toml
[manager]
append_keymap = [
	{ on = [ "g", "q" ], run = 'quit' },
]
```
