### DISCUSSION TITLE
Open current directory in new terminal tab

### DISCUSSION THREAD

**Discussion by membranobruno** [sxyazi/yazi#1829] [1. Q&A]
For example, I'm in react project directory and I want to open it in new tab quickly for start or editing. I don't believe it's not possible. Thanks a lot for any advice

**Comment by dawsers** [comment]
Change your key binding from `T` to whatever you want, and set your terminal executable where it says `kitty`

``` toml
[manager]
prepend_keymap = [
    { on = "T", run = "shell --orphan --confirm kitty", desc = "Open terminal at current dir" },
]
```
