### DISCUSSION TITLE
Store plugins and flavors in data folder (~/.local/share/yazi or $XDG_DATA_HOME/yazi)

### DISCUSSION THREAD

**Discussion by dangooddd** [sxyazi/yazi#1872] [4. Ideas]
I wonder is there a reason to store flavors and plugins in config directory? In my opinion, it is better to store it in data directory.

I think many people including me put those directories in gitignore because dont want to store plugin/flavor source code in their dotfiles repo.

Also, nvim for example stores plugins in data folder, so why we choose this approach?

**Comment by xfzv** [comment]
Agreed, this would be much cleaner.

As far as I'm concerned, I'm using [`chezmoi`](https://chezmoi.io/) to manage my dotfiles. `chezmoi` allows to [include dotfiles from elsewhere](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/) so I can have for example `~/dotfiles/.chezmoiexternals/yazi.toml`:

```toml
[".config/yazi/plugins/augment-command.yazi/init.lua"]
type = "file"
url = "https://raw.githubusercontent.com/hankertrix/augment-command.yazi/main/init.lua"
refreshPeriod = "168h"

[".config/yazi/plugins/chmod.yazi/init.lua"]
type = "file"
url = "https://raw.githubusercontent.com/yazi-rs/plugins/main/chmod.yazi/init.lua"
refreshPeriod = "168h"
```

With this approach:

- I don't have to add `yazi` plugins directory to `.gitignore` or `.chezmoiignore`
- The file is updated every 168 hours (customizable) when I run `chezmoi update` or `chezmoi apply` so I don't have to have the Git repo cloned locally and to run `git pull`.
