### DISCUSSION TITLE
Email selected files with Thunderbird

### DISCUSSION THREAD

**Discussion by anthonyco** [sxyazi/yazi#1886] [2. Show and tell]
To send selected files using Thunderbird, with a keybinding (in the example below, with Ctrl+S):
```toml
# ~/.config/yazi/keymap.toml
[[manager.prepend_keymap]]
on  = "<C-s>"
run = '''
    shell 'filenames=$(for path in "$@"; do echo $path; done | paste -s -d,);singlequoteslist=$(printf '"\'"%s"\'"' "$filenames");thunderbird -compose "attachment=$singlequoteslist"' --confirm
'''
```

It took me way too long, so hopefully this may save someone time. I proposed a change to the Tips section in the documentation, at https://yazi-rs.github.io/docs/tips. 
Only tested on Linux.
