### DISCUSSION TITLE
How to display hidden files and hidden folders in different colors

### DISCUSSION THREAD

**Discussion by Xiaomony** [sxyazi/yazi#2113] [1. Q&A] [answered]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Powershell

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (5cfcab3 2024-12-20)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.2 (5cfcab3 2024-12-20)

Emulator
    Brand.from_env      : Some(Microsoft)
    Emulator.detect     : Emulator { kind: Left(Microsoft), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.3

Variables
    SHELL           : None
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block-create: Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })
    block-rename: Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.45
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : program not found
    magick        : 7.1.1-43
    fzf           : 0.57.0
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.6
    7z/7zz        : program not found / program not found
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found
```

### Describe the question

I want to have the **hidden files and folders** displayed in another color instead of the default one.

### Checklist

- [X] I have searched the existing discussions/issues

**Comment by hankertrix** [comment, marked as answer]
In your `theme.toml` file, copy Yazi's default file type configuration from [here](https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme-light.toml#L209-L238).

Add a rule like `{ name = "*", is = "hidden", bg = "cyan"}` to the top of rules. Here's an example:

```toml
[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "yellow" },

    # Media
    { mime = "{audio,video}/*", fg = "magenta" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "cyan" },

    # Empty files
    # { mime = "inode/empty", fg = "red" },

    #############################################
    # Add the 2 lines below
    # Hidden files
    { name = "*", is = "hidden", bg = "cyan" },
    #############################################

    # Special files
    { name = "*", is = "orphan", bg = "red" },
    { name = "*", is = "exec", fg = "green" },

    # Dummy files
    { name = "*", is = "dummy", bg = "red" },
    { name = "*/", is = "dummy", bg = "red" },

    # Fallback
    # { name = "*", fg = "white" },
    { name = "*/", fg = "blue" },
]
```

Please also read this page:
https://yazi-rs.github.io/docs/configuration/theme#filetype
