### DISCUSSION TITLE
Latest version (25.4.8) might have broken `preview_hovered`

### DISCUSSION THREAD

**Discussion by niekdomi** [sxyazi/yazi#2595] [1. Q&A] [answered]
### What system are you running Yazi on?

wayland

### What terminal are you running Yazi in?

Ghostty 1.1.3-arch1

### `yazi --debug` output

```Shell
Yazi
    Version: 25.4.8 (Arch Linux 2025-04-09)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.86.0 (05f9846f 2025-03-31)

...
```

### Describe the question

Is it possible that the latest update to 25.4.8 might have broken the `preview_hovered`?

Heres my `theme.toml`

```toml
[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[manager]
preview_hovered = { reversed = true }
```

This option no longer seems to work. Not sure if this is an issue though or I just missed some breaking changes.

### Checklist

- [X] I have read all the documentation
- [X] I have searched the existing discussions/issues
