### DISCUSSION TITLE
How to make keymap.toml work?

### DISCUSSION THREAD

**Discussion by happyTonakai** [sxyazi/yazi#2844] [1. Q&A] [answered]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2

### `yazi --debug` output

```Shell
Yazi
    Version: 25.4.8 (Homebrew 2025-04-08)
    Debug  : false
    Triple : aarch64-apple-darwin (macos-aarch64)
    Rustc  : 1.86.0 (05f9846f 2025-03-31)

Ya
    Version: 25.4.8 (Homebrew 2025-04-08)

Emulator
    TERM                : Some("xterm-256color")
    TERM_PROGRAM        : Some("iTerm.app")
    TERM_PROGRAM_VERSION: Some("3.5.14")
    Brand.from_env      : Some(Iterm2)
    Emulator.detect     : Emulator { kind: Left(Iterm2), light: false, cell_size: None }

Adapter
    Adapter.matches    : Iip
    Dimension.available: WindowSize { rows: 48, columns: 160, width: 1760, height: 1008 }

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : Some("/bin/zsh")
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.41
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1.1 / 7.1.1
    pdftoppm      : 25.05.0
    magick        : 7.1.1-47
    fzf           : 0.62.0
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : No such file or directory (os error 2)
    zoxide        : 0.9.7
    7zz/7z        : 24.09 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)

Routine
    `file -bL --mime-type`: text/plain


See https://yazi-rs.github.io/docs/plugins/overview#debugging on how to enable logging or debug runtime errors.
```

### Describe the question

Hello everyone, I'm new to yazi and I'm trying to configure yazi to switch the keymaps of zoxide and fzf by:

```toml
# ~/.config/yazi/keymap.toml
[mgr]
prepend_keymap = [
{ on = "Z",         run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
{ on = "z",         run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },
]
```

But it is not working. I tried to remove all default keymap by
```toml
[mgr]
keymap = [
	# This will override all default keybindings, and just keep the two below.
	{ on = "<C-a>",      run = "my-cmd1" },
	{ on = [ "g", "b" ], run = "my-cmd2" },
]
```
which is the official example in the document but it doesn't work as well, the default keymaps are still working.

Am I missing something?

### Checklist

- [X] I have read all the documentation
- [X] I have searched the existing discussions/issues

**Comment by happyTonakai** [comment]
It seems that except themes.toml, both keymap.toml and yazi.toml are not working. I create a yazi.toml at ~/.config/yazi/ as:
```toml
# yazi.toml
[mgr]
show_hidden = true
```
but no hidden folders/files are shown.
