### DISCUSSION TITLE
"Show symlink in status bar" not working

### DISCUSSION THREAD

**Discussion by fritzrehde** [sxyazi/yazi#500] [1. Q&A] [answered]
I followed https://yazi-rs.github.io/docs/tips/#show-symlink-in-status-bar but it doesn't seem to work for me.
I have 
```lua
function Status:name()
	local h = cx.active.current.hovered
	if h == nil then
		return ui.Span("")
	end

	-- Show symlink if exists
	local linked = ""
	if h.link_to ~= nil then
		linked = " -> " .. tostring(h.link_to)
	end

	return ui.Span(" " .. h.name .. linked)
end
```
in `~/.config/yazi/plugins/status-name.yazi/init.lua`. Then, in `yazi.toml` I have:
```toml
[plugins]
preload = [
	"$XDG_CONFIG_HOME/yazi/plugins/status-name.yazi/init.lua"
]
```
but the symlink indicator text in the status bar is not showing up. Any ideas?
