### DISCUSSION TITLE
How do I prepend rules to [icon] in theme.toml?

### DISCUSSION THREAD

**Discussion by grig-iv** [sxyazi/yazi#640] [1. Q&A]
How to prepend rules to [icon] in theme.toml?

The straightforward way is just overwriting rules
```toml
[icon]
rules = [
    ...
]
```
