### DISCUSSION TITLE
How do I restore a file from trash?

### DISCUSSION THREAD

**Discussion by UtkarshVerma** [sxyazi/yazi#667] [1. Q&A]
Is there any way I can restore an accidentally deleted file that went to trash?

**Comment by sxyazi** [comment]
If you are on macOS/Windows, they will go into the system's trash/recycle bin, where you can recover them.

If you are on Linux, it will follow [The FreeDesktop.org Trash specification](https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html) and go into the directory specified by that specification. Most desktop environments adhering to this specification will abstract out a trash/recycle bin concept similar to macOS/Windows.

Of course, the best approach is to avoid accidental deletion. See the doc here https://yazi-rs.github.io/docs/configuration/keymap/#remove

**Reply by UtkarshVerma** [reply]
Thanks. The deletion does send it to the recycle bin. But I was just wondering if `yazi` supported a way to open the recycle bin and restore files to their original path.

For example, when I open the recycle bin in `thunar` on Linux, right clicking a file/folder presents me a "restore" option that automatically restores the file to its old path.

**Reply by sxyazi** [reply]
[trash-cli](https://github.com/andreafrancia/trash-cli) has a `trash-restore` command, I think you can bind a key to it through the `shell` command to do this, see https://yazi-rs.github.io/docs/configuration/keymap/#shell

**Comment by UtkarshVerma** [comment]
> [trash-cli](https://github.com/andreafrancia/trash-cli) has a `trash-restore` command, I think you can bind a key to it through the `shell` command to do this, see https://yazi-rs.github.io/docs/configuration/keymap/#shell

Thanks for your suggestion. I wrote a shell script to do it for me.

```sh
#!/bin/sh
# List deleted files/directories in $PWD using `fzf` and restore the selected ones.

deleted="$(printf "\n" | trash-restore |
    head -n -1 |
    awk -v filter="^${PWD}/[^/]*$" '$4~filter {print $1, $4}')"
ids="$(echo "$deleted" | fzf --multi | cut -d' ' -f1 | tr '\n' ',')"
ids="${ids%,}"

echo "$ids" | exec trash-restore >/dev/null
```

Since this script isn't actually required outside of yazi, I wish to inline it in `keymaps.toml`. However, I don't know how. Could you please let me know how it could be done?

I tried this but it doesn't work.

```toml
[[manager.prepend_keymap]]
desc = "Restore file"
on = ["R"]
exec = '''
	shell 'deleted="$(printf "\n" | trash-restore | head -n -1 | awk -v filter="^${PWD}/[^/]*$" '$4~filter {print $1, $4}')"
ids="$(echo "$deleted" | fzf --multi | cut -d' ' -f1 | tr '\n' ',')"
ids="${ids%,}"

echo "$ids" | exec trash-restore >/dev/null'  --block --confirm
'''
```
