### DISCUSSION TITLE
Using yazi in sudo

### DISCUSSION THREAD

**Discussion by Samthesurf** [sxyazi/yazi#669] [1. Q&A] [answered]
I set my editor as Neovim in my zshrc, but anytime, I use sudo yazi, I can't open any file with yazi, regardless of the file permissions, what do I do?

**Comment by sxyazi** [comment, marked as answer]
Hi! You can add a `sudo $EDITOR` opener to your `yazi.toml`:

```toml
[opener]
edit = [
  { run = 'sudo $EDITOR "$@"', block = true,  for = "unix" },
  # ...Your other openers
]
```

See the default openers here 

https://github.com/sxyazi/yazi/blob/681612f9764d45f61bbac622c57e0a48342b05c1/yazi-config/preset/yazi.toml#L28-L32

And the docs https://yazi-rs.github.io/docs/configuration/yazi#opener
