### DISCUSSION TITLE
Make smart enter configurable

### DISCUSSION THREAD

**Discussion by zebede22** [sxyazi/yazi#814] [4. Ideas]
I think there is no need it to be a separate plugin since many may wish it as a default behavior.
Maybe better to be configurable form `yazi.toml`:
```toml
[manager]
smart_enter = true
```
