### DISCUSSION TITLE
Open text files via nvim

### DISCUSSION THREAD

**Discussion by zebede22** [sxyazi/yazi#816] [1. Q&A] [answered]
I tried to config it this way:
`~/.config/yazi/yazi.toml`

```toml
[opener]
text = [{ run = 'nvim "$@"', block = true }]
```

But it didn't open in nvim when I try to open a file.

I tried to set $EDITOR variable: `set EDITOR=nvim` and it works.

Why the config not working?
