### ISSUE TITLE
open: ignore case for name globbing

### ISSUE THREAD

**Issue by Linus789** [sxyazi/yazi#146]
If I have for example this
```toml
[opener]
browser = [
	{ exec = 'chromium "$@"', display_name = "Open in Chromium" },
]

[open]
rules = [
	{ name = "*.html", use = ["browser"] },
]
```
and want to open a file called `test.HTML` it won't work. But it will work for `test.html`. Is there an easy way around that?

Edit: it seems to also apply to the theme icons.
