### ISSUE TITLE
Previewer appear very small

### ISSUE THREAD

**Issue by Felipe-9** [sxyazi/yazi#1676]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.36.2 created by Kovid Goyal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-04)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-nvim} \"$@\"", block: true, orphan: false, desc: "edit", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-nvim} \"$@\"", block: true, orphan: false, desc: "edit", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/felipepinto/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Any kind of media file appears very small instead of using the whole column

#### Image
<img width="1321" alt="Screenshot 2024-09-23 at 17 14 47" src="https://github.com/user-attachments/assets/d1412638-b63d-467b-adfd-deeb66b6cf7f">

#### PDF
<img width="1317" alt="Screenshot 2024-09-23 at 17 15 02" src="https://github.com/user-attachments/assets/8cc1f232-d463-4d2b-942c-daa8e7e77802">

#### This also happens when maximising the window
<img width="1510" alt="Screenshot 2024-09-23 at 17 37 33" src="https://github.com/user-attachments/assets/8607dcbc-5777-4e4e-9d67-c86ad9209694">

### Minimal reproducer

# tree
```
.
├── flavors
│   ├── LICENSE
│   ├── README.md
│   ├── catppuccin-mocha.yazi
│   ├── cspell.json
│   ├── package.json
│   ├── pnpm-lock.yaml
│   └── scripts
├── init.lua
├── keymap.toml
├── package.toml
├── plugins
│   ├── full-border.yazi
│   ├── glow.yazi
│   ├── max-preview.yazi
│   ├── miller.yazi
│   └── starship.yazi
├── theme.toml
└── yazi.toml

14 directories, 53 files
```

# init.lua
```lua
require("starship"):setup()
require("full-border"):setup {
  -- Available values: ui.Border.PLAIN, ui.Border.ROUNDED
	type = ui.Border.ROUNDED,
}

-- show ln in status-bar
function Status:name()
	local h = self._tab.current.hovered
	if not h then
		return ui.Line {}
	end

	-- return ui.Line(" " .. h.name)
  local linked = ""
  if h.link_to ~= nil then
    linked = " -> " .. tostring(h.link_to)
  end
  return ui.Line(" " .. h.name .. linked)
end
```

# package.toml
```toml
[plugin]
deps = [{ use = "yazi-rs/plugins:full-border", rev = "49ec78e" }]

[flavor]
deps = []
```
# yazi.toml
```toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true
show_symlink = true
syntect_theme = "~/.config/bat/themes/Catppuccin Mocha.tmTheme"
[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', desc = "edit", block = true, for = "unix" },
]
nvim = [
  { run  = 'nvim', desc = "nvim", block = true, for = "unix" },
]
play = [
	# { run = 'iina --mpv-force-window "$@"', orphan = true, for = "macos" },
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = 'mpv --force-window %*', orphan = true, for = "windows" },
	{ run = '''ffprobe "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
	# { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
zathura = [
  { run = 'zathura "$@"', orphan = true,  for = "unix" },
]
copy = [
  { run = 'pbcopy < "$@"', desc="copy", for = "macos" },
]
[open]
prepend_rules = [
  { mime = "application/pdf", use = [ "zathura", "open", "reveal" ] },
  { mime = "text/*", use = [ "edit", "copy", "reveal" ] },
  { name = "*/", use = [ "nvim", "edit", "open", "reveal" ] },
]
append_rules = [
  { name = "*", use = [ "edit", "copy", "open", "nvim", "reveal"] }
]
[plugin]
prepend_previwers = [
  # # HEIC previwer
  # { mime = "image/heic", run = "heic" }
  { name = "*.md", run = "glow" },
  { mime = "text/csv", run = "miller"},
  # { mime = "application/pdf", run = "zanthura"},
]
```
