### ISSUE TITLE
Contextual preview panel visibility

### ISSUE THREAD

**Issue by Acumane** [sxyazi/yazi#1708]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

Only show the preview panel for certain MIME types and optionally hide it on error/unsupported types. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Example: I really only care to see previews of images
```toml
# yazi.toml
[open]
rules = [
	# Folder
	{ name = "*/", use = [ "edit", "open", "reveal" ], preview = false },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal" ], preview = false },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ], preview = true  },
	# ...
]

```
(I know it's under `[open]` but we're already enumerating MIME types here, so...)

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature
