### ISSUE TITLE
No logs on windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sxyazi/yazi#195]
Hi! My config (`$HOME\AppData\Roaming\yazi\config\yazi.toml`)  reads:
```toml
[opener]
text = [
    { exec = 'vim.exe "$@"', block = true },
]
[log]
enabled = true
```
yet the file `$HOME\AppData\Roaming\yazi\state\yazi.log` remains empty.

Config: win10, pwsh-7.3.7, `yazi` installed from `scoop`:
```console
PS> yazi --version
yazi 0.1.4
```
