### ISSUE TITLE
Creating tabs quickly causes hovered item information to be lost

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#2155]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Ghostty 1.0.1-dev+0000000

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.3 (Arch Linux 2025-01-01)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.3 (Arch Linux 2025-01-01)

Emulator
    Brand.from_env      : Some(Ghostty)
    Emulator.detect     : Emulator { kind: Left(Ghostty), light: false, cell_size: Some((15, 30)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Ghostty), light: false, cell_size: Some((15, 30)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.3

Variables
    SHELL           : Some("/bin/bash")
    EDITOR          : Some("nvim")
    VISUAL          : Some("nvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.46
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.12.0
    magick        : 7.1.1-43
    fzf           : 0.57.0
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : No such file or directory (os error 2)
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : 24.09 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : 0.13
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

Creating tabs quickly, like by using the [smart switch tip](https://yazi-rs.github.io/docs/tips#smart-switch) causes the hovered item information on later tabs to be lost, specifically all tabs after the first one that is created.

### Minimal reproducer

Keybinds:
```toml
[[manager.prepend_keymap]]
on = [ "1" ]
run = "plugin smart-switch --args=0"
[[manager.prepend_keymap]]
on = [ "2" ]
run = "plugin smart-switch --args=1"
[[manager.prepend_keymap]]
on = [ "3" ]
run = "plugin smart-switch --args=2"
[[manager.prepend_keymap]]
on = [ "4" ]
run = "plugin smart-switch --args=3"
[[manager.prepend_keymap]]
on = [ "5" ]
run = "plugin smart-switch --args=4"
[[manager.prepend_keymap]]
on = [ "6" ]
run = "plugin smart-switch --args=5"
[[manager.prepend_keymap]]
on = [ "7" ]
run = "plugin smart-switch --args=6"
[[manager.prepend_keymap]]
on = [ "8" ]
run = "plugin smart-switch --args=7"
[[manager.prepend_keymap]]
on = [ "9" ]
run = "plugin smart-switch --args=8"
```

1. Use the [smart switch tip](https://yazi-rs.github.io/docs/tips#smart-switch).
2. Hover an item that isn't the first item.
3. Press a number that will create a lot of tabs, like `8` for example.
4. Observe that every tab after tab number `2` no longer hovers the item from step 2.

https://github.com/user-attachments/assets/57c80539-2198-4cf1-ae89-0255da598870

### Anything else?

I'm not sure if this bug is worth fixing since not many people use this tip, and it's not reproducible using the default key bind `t` to create a new tab. It's probably just down to how quickly Yazi can update the hovered item for the created tab after creating a tab, which is not fast enough for this use case.

I personally don't use this tip either.

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)
