### ISSUE TITLE
yazi.toml中控制面板比例的ratio设置在win终端中未生效

### ISSUE THREAD

**Issue by Zim-Inn** [sxyazi/yazi#2501]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

windows终端 1.22.10352.0

### `yazi --debug` output

```Shell
Yazi
    Version: 25.3.2 (46125ed 2025-03-02)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.85.0 (4d91de4e 2025-02-17)

Ya
    Version: 25.3.2 (46125ed 2025-03-02)

Emulator
    TERM                : None
    TERM_PROGRAM        : None
    TERM_PROGRAM_VERSION: None
    Brand.from_env      : Some(Microsoft)
    Emulator.detect     : Emulator { kind: Left(Microsoft), light: false, cell_size: Some((10, 20)) }

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : None
    EDITOR          : Some("D:\\IntelliJ IDEA 2024.2.4\\bin\\idea64.exe")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "idea64 %*", block: true, orphan: true, desc: "在Idea中编辑", for_: None, spread: true })
    block-create: Some(Opener { run: "idea64 %*", block: true, orphan: true, desc: "在Idea中编辑", for_: None, spread: true })
    block-rename: Some(Opener { run: "idea64 %*", block: true, orphan: true, desc: "在Idea中编辑", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.46
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : program not found
    magick        : program not found
    fzf           : 0.60.3
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.7
    7zz/7z        : program not found / 24.08
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found


See https://yazi-rs.github.io/docs/plugins/overview#debugging on how to enable logging or debug runtime errors
```

### Describe the bug

我希望调整面板比例以获得更大的预览区域,但是调整了ratio设置后却并未生效.
我的yazi.toml如下:
```toml
[Manager]
ratio = [1, 3, 4]
[opener]
edit = [
    { run = 'idea64 %*', block = true, orphan = true, for = "windows", desc = '在Idea中编辑' }
]

[preview]
wrap = "no"
max_width = 2000
max_height = 3000
cache_dir = ""
image_filter = "lanczos"
image_quality = 90
sixel_fraction = 20


[open]
rules = [
    # Folder
    { name = "*/", use = ["open", "edit", "reveal"] },
    # Text
    { mime = "text/*", use = ["edit", "reveal"] },
    # Image
    { mime = "image/*", use = ["open", "reveal"] },
    # Media
    { mime = "{audio,video}/*", use = ["play", "reveal"] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "reveal"] },
    # JSON
    { mime = "application/{json,ndjson}", use = ["edit", "reveal"] },
    { mime = "*/javascript", use = ["edit", "reveal"] },
    # Empty file
    { mime = "inode/empty", use = ["edit", "reveal"] },
    # Fallback
    { name = "*", use = ["reveal", "open"] },
]
```
我使用的yazi是从winget获取安装的,是winget中的最新版

### Minimal reproducer

在win11系统,如上版本win终端中可复现

### Checklist

- [x] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#binaries), and the issue is still reproducible
- [x] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [x] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)
