### ISSUE TITLE
Question - how to set custom keybind for escaping input field to normal mode?

### ISSUE THREAD

**Issue by infinite-ram** [sxyazi/yazi#2576]
Is it possible to setup custom keybinding to switch to **normal mode** in an input field?

#

For example: inside an input field, i would like to press `jj` to switch from insert mode to normal mode.

Currently, I can only switch to normal mode in input field only using `Esc` key:

https://github.com/user-attachments/assets/e80f2e3c-92b1-4967-a7a6-d224d115b888

<br>

Happy to provide more information.
Thanks.

**Comment by hankertrix** [comment]
This is possible by adding a keybind for the escape command in your `keymap.toml`.

Documentation:
https://yazi-rs.github.io/docs/configuration/keymap#input

Example:

```toml
# ~/.config/yazi/keymap.toml
[input]
on = ["j", "j"]
run = "escape"
desc = "Back to normal mode, or cancel input"
```

**Comment by infinite-ram** [comment]
Thanks for the response @hankertrix. 

That didn't seem to work for me.
Does it work for you?

Here is my `~/.config/yazi/keymap.toml` file:
```toml
[input]
prepend_keymap = [
  { on = ["j", "j"], run = "escape", desc = "Back to normal mode, or cancel input" },
]
```
