### ISSUE TITLE
Custom input box position

### ISSUE THREAD

**Issue by Hanaasagi** [sxyazi/yazi#351]
### Is your feature request related to a problem? Please describe

Hi, It would be gread to customize the position of the input box. Currently, yazi is hardcoded to display the input box at `x: 0, y: 2`. Because everyone's monitor size and position are different, for me, my focus is often in the middle of the screen. I would like to be able to define the display position of the input box in yazi.toml.

Related code:

https://github.com/sxyazi/yazi/blob/1bbb3235098da200e8d0d814fee554044ffaf5df/yazi-core/src/input/option.rs#L15-L22

### Will you be willing to contribute this feature?

- [X] Yes, I will try to implement it

### Describe the solution you'd like

Just a discussion, and I've thought of three configuration options

### 1. Fixed column and line offset

```toml
[input-box]
x  = 0
y = 2
```

### 2. Percentage

```toml
[input-box]
x  = 0
y = 0.2
```

20 % of the screen width. 

Btw, Fixed position and percentage aren't conflicting; we can distinguish them by checking for floating-point numbers less than 1.

### 3. Pre-defined position

```toml
[input-box]
position = "top/middle/bottom"
```

**Comment by Hanaasagi** [comment]
Hello, I have a few more questions. Once these are resolved, I can get started.

1. About where the configuration should be placed, I personally think it should be in `yazi.toml`. However, from another perspective, this configuration can also be considered part of the UI. Should it be placed in `theme.toml`? (I noticed that `theme.toml` already has sections for `input` and `select`.)

2. the meaning of x offset, currently, the code calculates x starting from half of the screen, and when `x=0`, it is centered. If someone has a left-align requirement, configuring it might be difficult (need to know halft width). 

Related code:
https://github.com/sxyazi/yazi/blob/7512b2c63ef129b40ebc24932747108099e143e4/yazi-core/src/context.rs#L34-L38

Furthermore, if we want to make window centering, we need the current terminal size, the width of the popup window, and the coordinates of the top-left corner of the popup. This is challenging to specify in the configuration file because the terminal size may change.

Inspired from some software practices, such as tmux, it supports preset strings to express predefined positions when popping up.

```
tmux popup -x R figlet "Right"
tmux popup -x 10 R figlet "10 columns from lefth"
```

ref: http://man.openbsd.org/OpenBSD-current/man1/tmux.1#display-menu

Maybe it's like this. 

```toml
[input]
[input.top]
x = "center"
# Or 20 columns offset from lefth
x = 20
# Or 20% offset from lefth
x = 0.2

y = 
width = 20 # or 0.2


```

But the `hovered_offset` should only need to fix the column offset, which makes the configuration a bit more complex. 🤯

**Comment by sxyazi** [comment]
> About where the configuration should be placed, I personally think it should be in yazi.toml

Good question! I've never thought about it. Adding it to `theme.toml` means the theme can modify the size of `Input` and `Select` (not just the style), and if users want to change the `Input` size, they would need to modify the theme file.

This is not conducive to future theme updates, as users would have to merge conflicts themselves. Maybe later we can include it in both `yazi.toml` and `theme.toml`, with `yazi.toml` taking precedence. For now, let's add it to `yazi.toml`!

> If someone has a left-align requirement, configuring it might be difficult (need to know halft width).

Is left-align a valid requirement? I'm not sure when it would be needed. Maybe we can add another type similar to `Top` for that scenario, starting from the top left corner. I haven't thought of a name for it yet, maybe even the name `Top` needs to be changed. Any ideas?

I find the tmux way too complex; it's not user-friendly (even for developers). I prefer offering a few initial preset positions, and users can fine-tune based on them (cells, percentages).

**Comment by Hanaasagi** [comment]
What do you think of this? Adding a `position` field, treating `top`, `hovered` etc., as predefined positions. Then users can make adjustments on this position using offsets.

```toml
[input]
# predefined position, default "top"
position = "top|top-left|hovered|bottom|center|..."
# column offset from the position., default 0
x_offset = 10 # -10 ...
# line offset from the position., default 0
y_offset = 20 # -20...
# width
width = 50
height = 1

[select]
# same

```
