### ISSUE TITLE
The sorting of the list after renaming is confusing

### ISSUE THREAD

**Issue by Hanaasagi** [sxyazi/yazi#390]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.12.3 (5efb0690)

### Yazi version

main 5439c80a03987fe286e721e0025b5ad4c4105615

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

https://github.com/sxyazi/yazi/assets/9482395/8eff3314-6b25-4a38-bbd9-6b79aa4ad070

some items move to middle, some else move to bottom.

### Expected Behavior

Not sure, but I think if the filenames are same, the position should not be changed.

### To Reproduce

Move to item and press `r` then `enter`. repeat...

### Configuration

yazi.toml
```toml
[manager]
# layout         = [ 0, 3, 7 ]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true

```

keymap.toml

```toml
[manager]

keymap = [

	{ on = [ "r" ],         exec = "rename --force",                                               desc = "Rename a file or directory" },
]

```
