### ISSUE TITLE
Simplify yazi.toml `input` and `select` sections

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#448]
I'm currently going through recent changes to the config preset and I noticed this addition:

```toml
[input]
# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]


# create
create_title  = "Create:"
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]


# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# ....
```

I'm thinking this could be simplified to:

```toml
[input]
# cd
cd = { title = "Change directory:", origin = "top-center", offset = [ 0, 2, 50, 3 ] }


# create
create = { title  = "Create:", origin = "top-center", offset = [ 0, 2, 50, 3 ] }


# rename
rename = { title  = "Rename:", origin = "hovered", offset = [ 0, 1, 50, 3 ] }

# ....
```

That would depend on being able to merge missing properties of input.cd/create/rename/etc with the default ones... just a thought. Might not be feasible 😅.
