### ISSUE TITLE
Allow unordered TOML in configs

### ISSUE THREAD

**Issue by fufexan** [sxyazi/yazi#458]
### Is your feature request related to a problem? Please describe

Currently there is at least one place in the configs that requires ordered entries. That is, in the `[icons]` section inside `theme.toml`. It expects `"*"` and `"*/"` icons to be set after all other entries in order to match the others properly, otherwise it simply shows the default icons for files/directories instead of the proper matches.

This is an issue that's come up after trying to change the icons in my Home Manager config, which sorts the entries lexicographically. While the issue would be way harder to solve in Home Manager itself, it doesn't sound too hard to fix in yazi's code.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi should not expect ordered entries and instead treat `"*"` and `"*/"` as special entries.

### Describe alternatives you've considered

I could manually write the toml file instead of relying on Home Manager to generate it from Nix code, but this would be a temporary solution.

**Comment by sxyazi** [comment]
I plan to convert icons into a list and support icon colors (https://github.com/sxyazi/yazi/issues/402), in the upcoming breaking change version v0.2.0.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/503

**Comment by fufexan** [comment]
@sxyazi I've just updated today and it seems the issue is not resolved. My `theme.toml` file is generated like this:

```toml
[[icon.rules]]
name = "*"
text = ""

[[icon.rules]]
name = "*/"
text = "󰉋"

[[icon.rules]]
name = ".config/"
text = ""

[[icon.rules]]
name = ".ssh/"
text = "󰢬"

[[icon.rules]]
name = "Desktop/"
text = ""

[[icon.rules]]
name = "Development/"
text = ""

[[icon.rules]]
name = "Documents/"
text = ""

[[icon.rules]]
name = "Downloads/"
text = "󰉍"

[[icon.rules]]
name = "Library/"
text = ""
# ...
```

And the `*` and `*/` icons still take precedence over all others. This does not happen when they're moved under all other rules.
