### ISSUE TITLE
Folder-local options for the file manager

### ISSUE THREAD

**Issue by jyothisv** [sxyazi/yazi#623]
### Is your feature request related to a problem? Please describe

First of all, thank you very much for this awesome project! I am impressed by Yazi's speed as well as features. I currently use lf and would love to switch over.

One feature that I really like in lf is the ability to set properties only in a specific directory. For example, we can use time-based sorting for say the Downloads directory while keeping natural sorting for all other directories. I think that would be a a nice addition to Yazi.

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

There should be an option to specify directory-specific settings in `yazi.toml`.  Probably we can add a list of directory, settings table under the `[manager]`.

An example: 
```toml
[[directory_local_settings]]
directory = "~/Downloads"
sort_by = "modified"
sort_reverse = true
```

If the directory name ends with a slash, the settings would be applied to its sub-directories as well.

A related feature would be a global option to make sorting commands always be directory-local. Usually, when I sort the files in a directory, I don't want the sorting to persist when I go to the parent directory. So this option would be quite useful to me.

**Comment by sxyazi** [comment]
Sounds good to me. Maybe we can have:
```toml
[folder]
rules = [
  { name = "Downloads/", sort_by = "modified", sort_reverse = true, preload = false, ... }
]
```

to keep the same style as others.
