### ISSUE TITLE
Pressing `enter` on folder name should drill down (focus) into that instead of opening folder in my editor

### ISSUE THREAD

**Issue by jamischarles** [sxyazi/yazi#645]
### Is your feature request related to a problem? Please describe

First off, I'm LOVING yazi. Really stellar work!

When I hit `enter` on a folder, I'd expect it to drill down into that path. Instead it currently opens netrw in neovim (whether I'm launching yazi from command line or inside neovim). I'm guessing that's because of the $EDITOR variable.

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

When I hit enter, I'd love for it to behave like `->` (right arrow) does

### Describe alternatives you've considered

1. Add another opener for path/folder
2. Remap enter key to do same action as `->`

### Additional context

I reviewed https://yazi-rs.github.io/docs/configuration/yazi/#opener and couldn't find any openers related to folder or path.

**Comment by jamischarles** [comment]
@Reledia Great suggestion. I got it working with `l` but wasn't able to override the `enter` key...

```toml
# keymap.toml
[[manager.prepend_keymap]]
on   = [ "l", "<Enter>" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.append_keymap]]
on   = [ "<Enter>" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[select.append_keymap]]
on   = [ "<Enter>" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
```
