### ISSUE TITLE
Add a new `[notify]` section to the `theme.toml` to configure the `notify` component's style

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#717]
### Please describe the problem you're trying to solve

The title style and icon of the `notify` component are currently hardcoded:

https://github.com/sxyazi/yazi/blob/e51e8ad789914b2ab4a9485da7aa7fbc7b3bb450/yazi-fm/src/notify/layout.rs#L44-L48

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add a new `[notify]` section to the `theme.toml` to configure the `notify` component's style:

```toml
[notify]
title_info  = { fg = "green" }
title_warn  = { bg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""
```
