### ISSUE TITLE
separator_style does not seem to be applied properly

### ISSUE THREAD

**Issue by Souheab** [sxyazi/yazi#858]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.4 (Arch Linux 2024-03-31)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/solo/.local/state/yazi" directory.
```

</details>

### Describe the bug

separator_style reversed attribute and fg attribute does not seem to be applied.

I have this in my theme.toml
```toml
[status]
separator_style = {bg = "reset", fg = "blue", reversed = true}
```
Here's how it looks like in the terminal
![image](https://github.com/sxyazi/yazi/assets/85948717/c2c1fa92-301f-4a4e-9160-1eafadea0ba6)

I tried this and it doesn't work either
```toml
[status]
separator_style = {bg = "blue", fg = "red"}
```
here's what this looks like in the terminal
![image](https://github.com/sxyazi/yazi/assets/85948717/7dc631ac-1495-47cf-805a-1e1b024beb35)

The bg seems to be applied correctly , but from what I can see fg and reversed are not applied.

### Expected Behavior

Expect seperator_style to be applied correctly

### To Reproduce

Put this in theme.toml and open the application

```toml
[status]
separator_style = {bg = "reset", fg = "blue", reversed = true}
```

### Configuration

here's my entire theme.toml status section
```toml
[status]
separator_open = ""
separator_close = ""
mode_normal = {bg = "reset", fg = "blue" , bold = true , reversed = true}
mode_select = {bg = "reset", fg = "red" , bold = true , reversed = true}
mode_unset = {bg = "reset", fg = "red" , bold = true , reversed = true}
separator_style = {bg = "reset", fg = "blue", reversed = true}
```
