### ISSUE TITLE
Disabling a key also disables key chords

### ISSUE THREAD

**Issue by Allaman** [sxyazi/yazi#899]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.33.0

### Did you try the latest code to see if this problem got fixed?

Not tried, and I'll explain why below

### `yazi --debug` output

<details>

```sh
Yazi
    yazi 0.2.4 (b10f2de 2024-03-09)

Environment
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

Ueberzug
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false
```

</details>

### Describe the bug

Sorry about the headline, I couldn't think of anything better.

I want to unbind `d` as trash command and bind it to `dd` (sorry, blame my muscle memory 😆 )

My approach is like so

```toml
# Unbind d
[[manager.prepend_keymap]]
on = [ "d" ]
run = ["dsagflasgd"]
desc = "Unbind default trash mapping"

# Use trash-cli to trash file
[[manager.prepend_keymap]]
on = [ "d", "d" ]
run = ['''
    shell --confirm 'trash-put "$@"'
''']
desc = "Move the files to the trash"
```

However, it does not work. I guess by mapping `d` to "noop" yazi ignores all following keystrokes and mappings?

### Expected Behavior

Hitting `dd` triggers the configured run command

### To Reproduce

see above toml snippet

### Configuration

see above toml snippet

**Comment by sxyazi** [comment]
Hi, this is the expected behavior. `prepend_keymap` is used to prepend items to the keymap, so the items appearing earlier have higher priority (matched first). Therefore, you can simply: 

```toml
[[manager.prepend_keymap]]
on = [ "d", "d" ]
run = ['''
    shell --confirm 'trash-put "$@"'
''']
desc = "Move the files to the trash"
```

without the need to unbind `d`, as it has been covered by `d => d` and will never match. Let me know if it works for you!
